### ISSUE TITLE
Please add latency compensation and calibration.

### ISSUE THREAD

**Issue by mysticallego** [RHeavenStudio/HeavenStudio#642]
### Describe your suggestion

On my system, I am struggling with a solid 40-50ms of delay even after turning down the audio buffer size. This makes it quite hard for me to play, since I often find I have to press earlier than I normally would when playing a rhythm game with calibration. Two sliders, one for audio video offset and one for judgement offset in ms would be perfect. A calibration test menu would also be a great addition, but optional.

### Additional context

I play many rhythm games at a high level, so I probably care more about calibration than most people. It's just one of those quality of life things I look for in a rhythm game, and since this is still in the early stages I figured I would put in the feature request now.

**Comment by ThatZeoMan** [comment]
Rhythm heaven fundamentally does not work with calibration. the visual animation of all minigames means that video, audio, and input offset just does not work with rhythm heaven. the best we can do is to reduce latency as much as possible, similar to Bits & Bops. Sorry! 🙏

**Comment by ThatZeoMan** [comment]
to be more specific, the way rhythm heaven is designed would essentially require turning back  time if we wanted to implement offset unlike other games where the input rating can be easily changed or set late.

**Comment by SomeNameDee** [comment]
There are other simpler delay-only possible implementations of calibration that would work with Heaven Studio, though.

1. Shift all visuals later, by an amount matching the input lag. This is an almost complete solution, except for the question of what to do about the sound effects generated by the player's inputs, since they'd have to be played before the judgement window, which I see a few (possibly configurable) possibilities for:
   - Just play the correct sound effect, and then replace it with the miss effect if the player then misses.
   - Play the player's sound effects unshifted (when they're made), even if they're out-of-sync with the rest of the cue sounds.
2. Don't shift visuals, but play the player's visuals unshifted. This means the player sprite may be out-of-sync with the other sprites, e.g. colliding with adjacent seals/locksteppers but not playing the got-hit animation.
3. Play the player's correct animation, then replace it with the miss animation if the player then misses.

I believe any of these approaches, alone or in combination, even if not perfect, would still be better than just offering no calibration option at all.
(Currently after as much setting-tweaking as possible, my delay is still 90±5 ms, which feels painful to play with)

**Comment by Rapandrasmus** [comment]
In Rhythm Heaven, the input animation and sound happen immediately when you input. Offsetting all the other sounds and visuals wouldn't help, and would actually make the experience worse, since everything would be even more desynced. So no calibration can be done, unless we want to change how rhythm heaven fundamentally works. Many games in the rhythm heaven series are designed around this, and have a lot of conditional fail states depending on how you input, which would look incredibly weird with the "play the correct state then the miss if player misses" idea.

Much like Bits & Bops, what can be done is improve the latency, be it by making a custom audio engine or making the most out of a fallback engine.

Heaven Studio does not have a custom audio engine and uses unity's audio engine, which is notorious for latency, since it was not made with rhythm games in mind.

I myself have created an audio engine using miniaudio implemented for godot to mitigate this exact issue for my own projects.
